![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [8]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Start coding here...
# Add as many cells as you like...

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

In [9]:
# Best math results(>= 640).
best_math_schools = schools[schools['average_math'] >= 640][['average_math', 'school_name']].sort_values('average_math', ascending=False)
best_math_schools

     average_math                                        school_name
88            754                             Stuyvesant High School
170           714                       Bronx High School of Science
93            711                Staten Island Technical High School
365           701  Queens High School for the Sciences at York Co...
68            683  High School for Mathematics, Science, and Engi...
280           682                     Brooklyn Technical High School
333           680                        Townsend Harris High School
174           669  High School of American Studies at Lehman College
0             657  New Explorations into Science, Technology and ...
45            641                      Eleanor Roosevelt High School

In [10]:
# Top 10 combined SAT scores.
schools['total_SAT'] = schools['average_math'] + schools['average_reading'] + schools['average_writing']

top_10_schools = schools[['total_SAT', 'school_name']].sort_values('total_SAT', ascending=False)
top_10_schools.head(10)

     total_SAT                                        school_name
88        2144                             Stuyvesant High School
170       2041                       Bronx High School of Science
93        2041                Staten Island Technical High School
174       2013  High School of American Studies at Lehman College
333       1981                        Townsend Harris High School
365       1947  Queens High School for the Sciences at York Co...
5         1914                     Bard High School Early College
280       1896                     Brooklyn Technical High School
45        1889                      Eleanor Roosevelt High School
68        1889  High School for Mathematics, Science, and Engi...

In [11]:
# Borough with largest standard deviation.
## calulating borough statistics.
borough_stats = schools.groupby('borough')['total_SAT'].agg(['count', 'mean', 'std']).round(2) 

## finding borough standard deviation.
largest_std_dev = borough_stats[borough_stats['std'] == borough_stats['std'].max()]
largest_std_dev = largest_std_dev.rename(columns={'count': 'num_schools', 'mean': 'average_SAT', 'std': 'std_SAT'})

largest_std_dev.reset_index(inplace=True)
largest_std_dev

     borough  num_schools  average_SAT  std_SAT
0  Manhattan           89      1340.13   230.29